/// Enum representing specific types of events that can occur within the Nimmsta SDK.
enum NimmstaEventType {
  /// Triggered when a barcode is successfully scanned.
  DID_SCAN_BARCODE,

  /// Triggered when the battery level of the device has changed.
  BATTERY_LEVEL_CHANGED,

  /// Triggered when a button on the device is clicked.
  DID_CLICK_BUTTON,

  /// Triggered when the device is disconnected from the application.
  DID_DISCONNECT,

  /// Triggered when the device connects and completes initialization.
  DID_CONNECT_AND_INIT,

  /// Triggered when the device reconnects and completes initialization.
  DID_RECONNECT_AND_INIT,

  /// Triggered when a generic event is received from the device.
  DID_RECEIVE_EVENT,

  /// Triggered when a touch event occurs on the device.
  DID_TOUCH
}

/// Represents an event generated by the Nimmsta SDK.
class NimmstaEvent {
  /// The type of event that occurred.
  final NimmstaEventType type;

  /// Optional data associated with the event, in the form of key-value pairs.
  final Map<String, dynamic>? data;

  /// Constructor to create a NimmstaEvent with the specified type and data.
  NimmstaEvent(this.type, this.data);

  @override
  String toString() => 'NimmstaEvent(type: $type, data: $data)';
}
