/// Enum representing specific types of events that can occur within the Nimmsta SDK.
enum NimmstaEventType {
  /// Triggered when a barcode is successfully scanned.
  didScanBarcode,

  /// Triggered when the battery level of the device has changed.
  batteryLevelChanged,

  /// Triggered when a button on the device is clicked.
  didClickButton,

  /// Triggered when the device is disconnected from the application.
  didDisconnect,

  /// Triggered when the device connects and completes initialization.
  didConnectAndInit,

  /// Triggered when the device reconnects and completes initialization.
  didReconnectAndInit,

  /// Triggered when a generic event is received from the device.
  didReceiveEvent,

  /// Triggered when a touch event occurs on the device.
  didTouch
}

/// Represents an event generated by the Nimmsta SDK.
class NimmstaEvent {
  /// The type of event that occurred.
  final NimmstaEventType type;

  /// Optional data associated with the event, in the form of key-value pairs.
  final Map<String, dynamic>? data;

  /// Constructor to create a NimmstaEvent with the specified type and data.
  NimmstaEvent(this.type, this.data);

  @override
  String toString() => 'NimmstaEvent(type: $type, data: $data)';
}
